### PR TITLE
issue #168 : disabled report creation menu item for closed phase

### PR DESCRIPTION
**Pull request by halfcurry**
#0000168 : "In the "Reports & documents" sub-tab, when the user clicks on the "New report" button, a drop-down menu appears and the report elements belonging to closed phases should appear as disabled.
Currently, they appear as enabled, but when the user clicks on it, nothing happen."
Hi, 
I fixed the issue by changing the style of the items which have closed phases.
Earlier, on hovering over a report from a closed phase, it turned orange, and appeared to be enabled.
image

Now, its background is gray and hovering over it does not change the color or cursor style.
image

I hope this is enough for showing it is disabled.

### CODE REVIEW

**Comment by osarrat** [comment]
Thanks for this work! I've updated the issue accordingly.
Just a bit more work to complete this easy first one.

**Comment by indianauthority97** [comment]
Hi, I just have to make the background of the disabled button transparent, right?
Or whatever the default background of the menu was there ( i.e  pale orange )?

**Comment by halfcurry** [comment]
Transparent means what exactly, please can you clarify ? Is it opacity ? Thanks.

**Comment by halfcurry** [comment]
Hi @osarrat , I made another commit. Please review it.
Thanks!

**Comment by osarrat** [comment]
Pull request tested locally.
Good work !
I merge it.

**Pull request merged**
