### PR TITLE
v2.2.0.1 for issue #1108

### PR DESCRIPTION
**Pull request by osarrat**

### CODE REVIEW

**Comment by osarrat** [comment]
Hi @numero-six ,
Would you have 5 minutes to look if everything seems fine for you in terms of git management for our first maintenance branch release ?
Best !

**Comment by ghost** [comment]
Well pom `<version>` should be `-SNAPSHOT` unless your plan is to tag 15aac8698e06f5d96544735bdfbb53aede7fcdee as `2.2.0.1`. If that is the plan, it's OK to merge.

Also, branch should start form `2.2`, not `2.2-rc6` but that's the same codebase so whatever, we don't care.

Do you want me to tag that as `2.2.0.1` or should we expect more fixes on `maintenance` branch before? I'm totally OK with both, your workflow matter most.

Also, I will merge `maintenance` into `master` so the bug will not come back in `2.3`.

**Comment by osarrat** [comment]
Thanks @numero-six for your feedbacks !
I have updated pom.xml <version> because I plan actually to tag that commit as v2.2.0.1.
I have branched from 2.2-rc6 instead of 2.2 because... I could'nt find anymore the v2.2 tag ! Is is still around ?

Once Codacy will have finished its check (postponed until now because I have added the maintenance branch to Codacy perimeter only now), I will merge this PR.
And since this work is out of your business perimeter, I will try to do the tagging myself after the merge.

Thanks once again !

**Comment by ghost** [comment]
You're doing it right 👍 but beware! tags should be consistent with `pom` so the tag is `2.2`, not `v2.2` and you should tag `2.2.0.1` not `v2.2.0.1` (`v` prefix may be seen often in git community but it's rarely/not used the Java world).

**Comment by osarrat** [comment]
Thanks for the feedback !
Tag renamed just now.
Thanks !

**Pull request merged**
