### PR TITLE
Second sprint from AtolCD

### PR DESCRIPTION
**Pull request by ftavin**
Mantis issues: (work in progress)
- adding contacts (#634)
- adding group iterations (#501)

### CODE REVIEW

**Comment by ghost** [comment]
Well travis raise a big concern here. You wrote a migration that require the database user to be superuser:

```
Must be superuser to create this extension.
```

That is due to V9__dedupe_contacts.sql

It adds a prerequisite for the database account and I'm pretty sure no sysadmin will allow that. Do you have a way to prevent this?

**Comment by ftavin** [comment]
Looks like a limitation due to the flyway mechanism to me. We need the pg_trgm module to be activated. If this requires to be superuser, this cannot be done using flyway and must be removed from the script and done manually by the administrator... :(

**Comment by ghost** [comment]
Well, it can't find any better way than doing it manually. I will update the installation procedure. Can you remove the line from the migration file?

**Comment by ghost** [comment]
OK, I'm trying to make travis OK with this extension issue. Can you

``` sh
git cherry-pick ca98b65bb6643256af42191ad86d34722d627b2e
```

**Comment by ftavin** [comment]
I just pulled the master branch and rebased v2.2-atol onto it.

**Comment by ghost** [comment]
Now, travis seems to install the extension

> $ psql --username postgres --command "CREATE EXTENSION IF NOT EXISTS pg_trgm;"
> CREATE EXTENSION

but it's like it's not available for the sigmah database :disappointed: I tried a new fix. Can you rebase again? Sorry for that.

**Comment by ftavin** [comment]
Done

**Comment by ghost** [comment]
OK, one last rebase and we get rid of that.

I tested and i guess you should get a brand new problem:

```
constraint "uk_ev3lt5f4afcgkonu6exlm9be8" of relation "value" does not exist
```

You are trying to drop a foreign key but I can't find where it was created. I found some FK on the "value" table in the V1 script but not this one. Can you investigate?

**Comment by ghost** [comment]
It seems you are adding work to this PR (commit 78e7394), i thought it was finished so I removed the WIP tag, was I wrong?

Don't forget you will still be able to submit PR after this one before the final release.

**Comment by ftavin** [comment]
Yes, we had some late work to push on friday. It is ok now.

**Comment by ghost** [comment]
Sorry for my error, next time don't hesitate to warn me: it would have been bad to merge unfinished work!

Can you fix the build until it's all green?

**Comment by ftavin** [comment]
I can't figure out what's wrong right now as we don't have those errors here. I'll try to take a look later this week.

**Comment by ghost** [comment]
Travis build says

> Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on org.sigmah.server.domain.value.Value.layoutGroupIteration references an unknown entity: org.sigmah.server.domain.layout.LayoutGroupIteration

I guess it's something like `LayoutGroupIteration` entitty not being declared somewhere in a `persitence.xml` file (the one for tests?) or something.

**Comment by ftavin** [comment]
Looks like everything is ok now !

**Comment by ghost** [comment]
Thanks!

The PR is too big and github doesn't allow me to put contextualized comments. Can you:
- add a javadoc on class `org.sigmah.client.util.ImageProvider` to explain the class role at the global application level?
- review your `throw new IllegalStateException();` to always include context in message (most of the time, it's the value of the enumeration)
- fix identations (2 spaces vs other styles)

I hope to merge today.

**Comment by osarrat** [comment]
Congrats @ftavin for that, and thanks both of you for your efforts !

**Comment by osarrat** [comment]
Yoohoo !!! Great ! 2.2-rc1 is almost here !

**Pull request merged**
