### PR TITLE
Fixed the pom to build the budget ratio migration tool (fixes #957)

### PR DESCRIPTION
**Pull request by Raphcal**

### CODE REVIEW

**Comment by osarrat** [comment]
GREAT ! Thanks @Raphcal for that !
I'll try it right now.

**Comment by osarrat** [comment]
Build successful with "mvn install" from the "migration_budget_field" folder !
But execution failed.. I get an "Erreur : impossible de trouver ou charger la classe principale update_database.Migrate" error while running "java -jar migrate-jar-with-dependencies.jar" from the "migration_budget_field/target" folder.
@Raphcal , is it working on your side ?

**Comment by Raphcal** [comment]
@osarrat Yes it is working for me:

```
$ mvn clean install
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.011 s
[INFO] Finished at: 2016-10-14T14:44:08+02:00
[INFO] Final Memory: 18M/140M
[INFO] ------------------------------------------------------------------------

$ java -jar target/migrate-jar-with-dependencies.jar 
usage: java -jar migrate.jar 'Path Config File'
ex: java -jar migrate.jar config.properties
```

**Comment by osarrat** [comment]
I confirm that the fix does resolve issue #957. So this PR can be merged.

**Comment by ghost** [comment]
I would have favored a flyway Java migration but this is much better than present state.

**Pull request merged**
