### PR TITLE
0000632: Replace "delete" icon by "link_delete" on delete project lin…

### PR DESCRIPTION
**Pull request by niksj**
fix for [0000632](http://www.sigmah.org/issues/view.php?id=632)

### CODE REVIEW

**Comment by ghost** [comment]
Hi @niksj, thank you for you PR. Could you tell me from where the `link_delete` file you added come from? I want to check that it's OK about license issues.

**Comment by niksj** [comment]
Hello @numero-six , 
I added it from codefisher.org site [Here](https://codefisher.org/pastel-svg/icon/link-delete/) 
It is also free available at iconfinder.com [Here](https://www.iconfinder.com/icons/5465/delete_link_icon#size=16)

**Comment by osarrat** [comment]
Hi @niksj !
Good for the addition of the link_delete icon as new resource.
But in GWT, we try not to update directy any CSS, but always to write Java code. So best solution will be to play with the Linked Project View in org.sigmah.client.ui.view.project .. You are closed to finish this issue!

**Comment by niksj** [comment]
Closing this as the error log suggests.

**Pull request closed without merging**
