### PR TITLE
Fixed global export when model includes iterative groups (fixes #1039)

### PR DESCRIPTION
**Pull request by Raphcal**
Fixes global export bug introduced when refactoring the GlobalExport
code.

### CODE REVIEW

**Comment by osarrat** [comment]
BRAVO !!
I'm eager to test this as soon as possible !

**Comment by osarrat** [comment]
Thanks @Raphcal for your latest commit  6a21fa !
But it seems more related to PR #68 than this PR #80. Can you confirm this commit has to be linked to this PR #80 ?

**Comment by Raphcal** [comment]
@osarrat Yes sorry, I made a mistake when selecting the branch for the commit. It is now fixed.

**Comment by osarrat** [comment]
@numero-six , can you check and merge this PR ?

**Pull request merged**
