### PR TITLE
Disable Offline Mode

### PR DESCRIPTION
**Pull request by ftavin**
- temporary (for v2.2)
- according to indications from rcalabro (see Mantis)

I'm not sure on which branch I have to make this pull-request (this commit isn't supposed to be used out of v2.2). I selected master, by default, but tell me if I'm wrong...

I had no time to test it (offline mode is not easy to test on a developper's environment), I just followed indications from rcalabro.

### CODE REVIEW

**Comment by osarrat** [comment]
In my opinion, it is correct to have the disabling to the offline mode as part of the "master" branch since v2.2 will be openly without the offline mode.
And an "Enable Offline mode" feature request (=> #1068) has been added in the roadmap to track its reactivation.

**Comment by osarrat** [comment]
@numero-six , can you check and merge this PR ?

**Comment by ghost** [comment]
> an "Enable Offline mode" feature request (=> #1068) has been added in the roadmap to track its reactivation.

Great idea. Maybe it should mention the commit to revert or this PR.

(PS: Sorry for delay, was on sick days :face_with_thermometer:)

**Comment by osarrat** [comment]
Good idea: I have updated the feature request #1068 accordingly.

And good to see you back ! (thanks for the merge)

**Pull request merged**
