### PR TITLE
Refractoring: removing GIN dependency injection and replacing by defered binding. Issue #1080

### PR DESCRIPTION
**Pull request by zak905**
GIN is outdated and not maintained anymore and it's near its end of life. It also causes Null pointer exceptions during dev mode. It's better not to not use it, and replace by a a simple interface (Client factory) that implements all the dependency injection of the project, and use deffered binding instead.
 This PR removes all the GIN (@Inject, @Singelton,..) DI classes and and annotations and replaces it by a manual DI mechanism implemented in ClassFactory and ClassFactoryImpl. it also removes the GIN dependency from the pom.xml. The project has been tested after the changes and it launches much faster during Dev mode.

### CODE REVIEW

**Comment by osarrat** [comment]
I'm personnally in favor of this PR. +1
Let's see what other might think about it before merging.

**Review by osarrat — APPROVED** [review]
I'm personnally in favor of this PR. 
Let's see what other might think about it before merging.

**Comment by zak905** [comment]
So any updates for this pull requests?

**Comment by osarrat** [comment]
@numero-six @Raphcal , would you have any brief 👍 or 👎 to give to us about this work ?

**Comment by zak905** [comment]
Anything new about this PR? 
IMO and from my personal experience, you really need to get rid of GIN because it's deprecated and not supported anymore. The next version of GWT 3.0 will not support Generators so GIN will be out. Another important point is that, in your project, dev mode does not work because GIN throws some NPE for some reason. Without dev mode, you will not be able to be productive to get developments quickly up. If this does not convince you guys yet, then we can close this PR.

**Comment by zak905** [comment]
Dear @Raphcal,

when you provide a :-1: for a PR, you have to provide an explanation why. At least, this is how it is done in open source projects. This seems like a waste of time. Closing the PR.

**Pull request closed without merging**
