### PR TITLE
Missing French translation for "Rename iteration" button (#1030)

### PR DESCRIPTION
**Pull request by osarrat**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @osarrat I'm struggling with this one. The good news is that line-ending (CRLF vs LF) seems to be OK from you now. 

But I still have issues with your IDE which seems to automatically make big changes on the `.properties` files:
* changing indentation (adding and removing spaces in comment sections)
* escaping unicode characters (replacing all accents with \uXXXX sequences...) which are just making the file harder to reader

Can you change your IDE settings to prevent that and recommit the file? I guess you only added 3 lines to the bundles but as you can see it's drowned all the noisy modifications. The diff should only contain the 3 lines added in the two .properties file.

**Comment by osarrat** [comment]
Thanks @numero-six  for your feedback.

I looked in the Netbeans documentation and forum, and didn't find anything to prevent the second issue (escaping unicode characters). But actually, according to the `[diff made on the commit](https://github.com/osarrat/sigmah/commit/d423ad98e57398804524e5270652ec4fd3ec28d3#diff-c019d4ea31094a75158495ebb2c25617)` which has modified this properties file, the properties file used already escaped unicode characters. And this might also be the case of Zanata or Pootle that we use to translate the full properties files. So is that ok if we keep unicode characters escaped ?

Regarding indentation, I used the [documented parameters in the wiki](http://wiki.sigmah.org/doku.php?id=contributorguide:netbeans#configure_indentation_settings) . So there should not be any issue here neither.

But according to the diff, the issue seems to be actually about line-endings since all line seems to be different in the diff. So I have tried to update the line-endings to LF, and force a new empty line in the file to have a difference able to make a commit. And I committed, and I see that there is still a conflict...

Sir, what should I do ?!

**Comment by ghost** [comment]
I've got it... look at [this diff from @Raphcal](
https://github.com/sigmah-dev/sigmah/pull/66/files#diff-c019d4ea31094a75158495ebb2c25617), taking `flexibleElementBudgetDistribution` as an example: you escape unicode like `\u00e9` but Raphaël escape with `\u00E9`: the uppercase/lowercase `E` makes the difference and that's why the file so much lines are modified at every pull-request...

I'm merging this one but we should find a way to make everyone follow the same conventions.

**Comment by osarrat** [comment]
Thanks @numero-six !

In order to move forward for all of us on those issues, I have added the two following recommendation for Netbeans IDE users in http://wiki.sigmah.org/doku.php?id=contributorguide:netbeans#recommended_netbeans_parameters_recommendations_for_more_comfort

- End-of-line management: Sigmah uses LF as standard character for end-of-line. In addition to the git config command recommended for Windows users when preparing their build environment , you can install the “Show and change line endings” plugin.
- Unicode escape characters (ie: \u00e9) management: Sigmah uses lower case Unicode escape characters. So when editing a properties file which has Unicode escape characters, you can use the command “Convert unicode chars to lowercase” available in the context menu. This command has to be installed through the plugin “Change case of unicode characters”.

**Pull request merged**
