### PR TITLE
Show value in Type column for just attached file.  Resolves #1046 

### PR DESCRIPTION
**Pull request by Seal98**
The fix for issue #0001046: Type column empty for just attached file in "Reports & documents" sub-tab

### CODE REVIEW

**Comment by osarrat** [comment]
Thanks for this work @Seal98 !
It is a good first step. In order to make your pull request more readable, I would advise you to start again your work on a separate iss1046 branch after having applied the recommendation on end-of-line management ([here](http://wiki.sigmah.org/doku.php?id=contributorguide:preparebuildenvironment#step_2get_a_local_copy_of_the_source) and [there](http://wiki.sigmah.org/doku.php?id=contributorguide:netbeans#recommended_netbeans_parameters_recommendations_for_more_comfort)). I would also advise you to follow recommendation on commits naming.
But that's already a good start. Congrats !

**Comment by osarrat** [comment]
Good to have make clearer your pull request title !
But I still advise you to restart from scratch your commits to take into account my former comment.
Best,
osarrat.

**Comment by Seal98** [comment]
Hello @osarrat 
Thank you for review.
These days I thought a lot about what I did wrong when committed my changes to GitHub. Why so many changed strings where shown in the AttachFilePresenter file. I've read provided by  you  Sigmah recommendation on end-of-line management, made double check. read GitHub help docs and stackoverflow answers. I tried everything : commit using NetBeans Git plugin, using Eclipse Git plugin, using Git cmd but nothing helped. And..finally..bingo - gotcha!
The was not my fault:)

I found that AttachFilePresenter.java has **\r\n (CRLF) line breaks in file in source Sigmah master branch.**
That why when committed my changes the CRLF were converted to LF and every string with the conversion was marked as changed.

How I found that? I've downloaded Sigmah source zip file. Extracted all files and investigated files using Notepad++ editor to see what line breaks symbols used there.

Here is AttachFilePresenter with 349 CRLF found

image

Here is EditReportDialog also from  downloaded Sigmah source zip file. 0 CRLF found

image

I went further and checked all *.java files in Sigmah source zip.

1818 java files in Sigmah.zip and 222 files have 49042 CRLF  hits

image

**So my question is** - can I now create separate iss1046 branch and commit my changes (the changes will include also changes due to CRLF to LF convertion) taking into account  recommendation on commits naming ? 
Or it would better to wait till you or somebody else will fix and update all files having CRLF line breaks in master branch?
I would prefer to not wait. Because I want to have my 1st fix applied before GSOC2017 application deadline:)

I am waiting your answer.
Thank  you,

With best regards, Alex.

**Comment by osarrat** [comment]
Hi Alex,

Thanks for your detailed report about line-endings. We are aware of this issue which is a common issue on many projects whose developers are either on Windows or Linux.
Have you checked the two part of the contributor guide I mentionned: ([here ](http://wiki.sigmah.org/doku.php?id=contributorguide:preparebuildenvironment#step_2get_a_local_copy_of_the_source)and [there](http://wiki.sigmah.org/doku.php?id=contributorguide:netbeans#recommended_netbeans_parameters_recommendations_for_more_comfort)) ?

My recommendation is again for you to start all your work in a brand new branch in which you will not only solve this issue #1046, but also produce a commit which avoid this line-endings problem. This is a good exercise for you to be able to contribute properly on the Sigmah project or other open-source projects having this similar situation regarding line-endings.

Once you will have finished this issue, you can come back to us on sigmah-dev mailing list to request another low hanging fruit one.  

Good luck !

**Comment by Seal98** [comment]
Hello Olivier,
I've applied the recommendation on end-of-line management and checked git setting and see that core.autocrlf is set to true.
I've created separate branch named iss1046 and made there only changes which are related to fix issue #1046. After that I made: add to index. commit with comment, push to remote branch in my github and created pull request.
With best regards, Alex

**Pull request closed without merging**
